### ISSUE TITLE
How would i get the Task History of a Ticket

### ISSUE THREAD

**Issue by abon22** [LPGhatguy/AutoTaskInterface#1]
Hi,
Can you help me on how to retrieve the Task History of a Ticket?
Is there a way for example, i would get the TaskID=123 and will retrieve Ticket History?

Sample Image below.
![2017-01-13_8-08-42](https://cloud.githubusercontent.com/assets/17940369/21913568/0b816368-d968-11e6-8d58-6208ba20f2cc.jpg)

I Just want to get the Date for Every Action Taken. 
Hope you can help me with this. Thank you.

**Comment by LPGhatguy** [comment]
I'm not sure! When I wrote the code in this repository, we didn't need to retrieve ticket history.

I haven't used AutoTask in a number of years and I don't have access to an install anymore, so I don't think I can be of any help.

**Comment by abon22** [comment]
No Problem. Thank you. :)
